name: thaishield_ai
description: "ThaiShield AI - Travel Safety Companion"
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.6
  google_maps_flutter: ^2.10.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.3.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  geolocator: ^14.0.3
  geocoding: ^4.0.0
  image_picker: ^1.2.2
  google_mlkit_text_recognition: ^0.15.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#0A1810"
  adaptive_icon_foreground: "assets/images/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
