import 'package:flutter/material.dart';

/// Small shared UI-string table for chrome text (nav labels, headers,
/// placeholders) that isn't covered by the ARB-based localization.
/// Falls back to English if the current locale has no entry for a key.
const Map<String, Map<String, String>> _appText = {
  'nav_home': {
    'th': 'หน้าแรก',
    'en': 'Home',
    'zh': '首页',
    'ko': '홈',
    'ru': 'Главная',
    'ja': 'ホーム',
  },
  'nav_scan': {
    'th': 'สแกน',
    'en': 'Scan',
    'zh': '扫描',
    'ko': '스캔',
    'ru': 'Скан',
    'ja': 'スキャン',
  },
  'nav_map': {
    'th': 'แผนที่',
    'en': 'Map',
    'zh': '地图',
    'ko': '지도',
    'ru': 'Карта',
    'ja': 'マップ',
  },
  'nav_sos': {
    'th': 'SOS',
    'en': 'SOS',
    'zh': 'SOS',
    'ko': 'SOS',
    'ru': 'SOS',
    'ja': 'SOS',
  },
  'nav_profile': {
    'th': 'โปรไฟล์',
    'en': 'Profile',
    'zh': '我的',
    'ko': '프로필',
    'ru': 'Профиль',
    'ja': 'プロフィール',
  },
  'home_tagline': {
    'th': 'เที่ยวปลอดภัย ฉลาดขึ้น',
    'en': 'Travel Safe · Stay Smart',
    'zh': '安全旅行 · 智慧出行',
    'ko': '안전한 여행 · 스마트한 선택',
    'ru': 'Безопасные путешествия · Будьте умнее',
    'ja': '安全な旅 · スマートに',
  },
  'feature_scanner_subtitle': {
    'th': 'สแกนเมนู ตรวจสอบราคา',
    'en': 'Scan menus, check prices',
    'zh': '扫描菜单，检查价格',
    'ko': '메뉴 스캔, 가격 확인',
    'ru': 'Сканируйте меню, проверяйте цены',
    'ja': 'メニューをスキャンして価格を確認',
  },
  'feature_map_subtitle': {
    'th': 'แผนที่พาร์ทเนอร์ & โซนเตือนภัย',
    'en': 'Partner map & alert zones',
    'zh': '合作伙伴地图和警示区域',
    'ko': '파트너 지도 및 알림 구역',
    'ru': 'Карта партнёров и зоны оповещения',
    'ja': 'パートナーマップとアラートゾーン',
  },
  'feature_sos_subtitle': {
    'th': 'พูดภาษาอังกฤษ สื่อสารทันที',
    'en': 'Speak English, communicate instantly',
    'zh': '说英语，即时沟通',
    'ko': '영어로 말하면 즉시 소통',
    'ru': 'Говорите по-английски — мгновенное общение',
    'ja': '英語で話して即時に伝える',
  },
  'profile_title': {
    'th': 'โปรไฟล์',
    'en': 'Profile',
    'zh': '个人资料',
    'ko': '프로필',
    'ru': 'Профиль',
    'ja': 'プロフィール',
  },
  'profile_language': {
    'th': 'ภาษา',
    'en': 'Language',
    'zh': '语言',
    'ko': '언어',
    'ru': 'Язык',
    'ja': '言語',
  },
  'profile_about_title': {
    'th': 'เกี่ยวกับ ThaiShield AI',
    'en': 'About ThaiShield AI',
    'zh': '关于 ThaiShield AI',
    'ko': 'ThaiShield AI 정보',
    'ru': 'О ThaiShield AI',
    'ja': 'ThaiShield AI について',
  },
  'scanner_coming_soon': {
    'th': 'เฟส 3 — เร็วๆ นี้',
    'en': 'Phase 3 — Coming Soon',
    'zh': '第三阶段 — 即将推出',
    'ko': '3단계 — 출시 예정',
    'ru': 'Этап 3 — скоро',
    'ja': 'フェーズ3 — 近日公開',
  },
  'sos_coming_soon': {
    'th': 'เฟส 4 — เร็วๆ นี้',
    'en': 'Phase 4 — Coming Soon',
    'zh': '第四阶段 — 即将推出',
    'ko': '4단계 — 출시 예정',
    'ru': 'Этап 4 — скоро',
    'ja': 'フェーズ4 — 近日公開',
  },
  'travel_alerts_title': {
    'th': 'การแจ้งเตือนการเดินทางในไทย (เรียลไทม์)',
    'en': 'Real-Time Thailand Travel Alerts',
    'zh': '泰国实时旅行提醒',
    'ko': '태국 실시간 여행 알림',
    'ru': 'Актуальные оповещения о поездках по Таиланду',
    'ja': 'タイ リアルタイム旅行アラート',
  },
  'travel_alerts_view_details': {
    'th': 'ดูรายละเอียด',
    'en': 'View details',
    'zh': '查看详情',
    'ko': '자세히 보기',
    'ru': 'Подробнее',
    'ja': '詳細を見る',
  },
  'travel_alerts_empty': {
    'th': 'ยังไม่มีข้อมูลการแจ้งเตือนในขณะนี้',
    'en': 'No travel alerts at the moment',
    'zh': '目前没有旅行提醒',
    'ko': '현재 여행 알림이 없습니다',
    'ru': 'Сейчас нет оповещений о поездках',
    'ja': '現在、旅行アラートはありません',
  },
  'travel_alerts_error': {
    'th': 'ไม่สามารถโหลดข้อมูลการแจ้งเตือนได้ในขณะนี้',
    'en': 'Unable to load travel alerts right now',
    'zh': '目前无法加载旅行提醒',
    'ko': '지금은 여행 알림을 불러올 수 없습니다',
    'ru': 'Не удалось загрузить оповещения о поездках',
    'ja': '現在、旅行アラートを読み込めません',
  },
  'travel_alerts_disclaimer': {
    'th': 'ข้อมูลนี้รวบรวมจากแหล่งข่าวสาธารณะเพื่อประกอบการตัดสินใจเท่านั้น กรุณาตรวจสอบกับแหล่งข้อมูลทางการก่อนเดินทาง',
    'en': 'This information is aggregated from public news sources for informational purposes only. Please verify with official sources before traveling.',
    'zh': '此信息汇总自公开新闻来源，仅供参考。出行前请以官方信息为准。',
    'ko': '이 정보는 공개 뉴스 소스에서 수집한 것으로 참고용입니다. 여행 전 공식 정보를 확인하세요.',
    'ru': 'Эта информация собрана из открытых новостных источников и носит исключительно информационный характер. Перед поездкой уточните данные в официальных источниках.',
    'ja': 'この情報は公開ニュースソースから集約したもので、参考情報です。旅行前に公式情報をご確認ください。',
  },
  'alert_category_flood': {
    'th': 'น้ำท่วม', 'en': 'FLOOD', 'zh': '洪水', 'ko': '홍수', 'ru': 'ПАВОДОК', 'ja': '洪水',
  },
  'alert_category_fire': {
    'th': 'ไฟไหม้', 'en': 'FIRE', 'zh': '火灾', 'ko': '화재', 'ru': 'ПОЖАР', 'ja': '火災',
  },
  'alert_category_storm': {
    'th': 'พายุ', 'en': 'STORM', 'zh': '风暴', 'ko': '폭풍', 'ru': 'ШТОРМ', 'ja': '暴風',
  },
  'alert_category_earthquake': {
    'th': 'แผ่นดินไหว', 'en': 'EARTHQUAKE', 'zh': '地震', 'ko': '지진', 'ru': 'ЗЕМЛЕТРЯСЕНИЕ', 'ja': '地震',
  },
  'alert_category_accident': {
    'th': 'อุบัติเหตุ', 'en': 'ACCIDENT', 'zh': '事故', 'ko': '사고', 'ru': 'ПРОИСШЕСТВИЕ', 'ja': '事故',
  },
  'alert_category_other': {
    'th': 'แจ้งเตือน', 'en': 'ALERT', 'zh': '提醒', 'ko': '알림', 'ru': 'ОПОВЕЩЕНИЕ', 'ja': 'アラート',
  },
  'home_active_alerts_title': {
    'th': 'การแจ้งเตือนที่กำลังเกิดขึ้นในไทย',
    'en': 'Active Alerts in Thailand',
    'zh': '泰国当前提醒',
    'ko': '태국 내 활성 알림',
    'ru': 'Текущие оповещения по Таиланду',
    'ja': 'タイの現在のアラート',
  },
  'home_active_alerts_view_map': {
    'th': 'ดูแผนที่', 'en': 'View Map', 'zh': '查看地图', 'ko': '지도 보기', 'ru': 'Смотреть карту', 'ja': '地図を見る',
  },
  'home_alerts_unit': {
    'th': 'รายงาน', 'en': 'reports', 'zh': '条', 'ko': '건', 'ru': 'сообщений', 'ja': '件',
  },
  'home_alerts_summary_generic': {
    'th': 'มีการแจ้งเตือน {count} รายการในไทย',
    'en': '{count} active reports in Thailand',
    'zh': '泰国目前有 {count} 条提醒',
    'ko': '태국 내 활성 알림 {count}건',
    'ru': '{count} активных оповещений по Таиланду',
    'ja': 'タイで{count}件のアラートがあります',
  },
  'home_top_news': {
    'th': 'ข่าวเด่น', 'en': 'Top News', 'zh': '头条新闻', 'ko': '주요 뉴스', 'ru': 'Главные новости', 'ja': 'トップニュース',
  },
  'home_see_all': {
    'th': 'ดูทั้งหมด', 'en': 'See all', 'zh': '查看全部', 'ko': '전체 보기', 'ru': 'Смотреть все', 'ja': 'すべて見る',
  },
  'home_useful_tools': {
    'th': 'เครื่องมือที่ใช้บ่อย', 'en': 'Useful Tools', 'zh': '实用工具', 'ko': '유용한 도구', 'ru': 'Полезные инструменты', 'ja': '便利な機能',
  },
  'tool_safety_tips': {
    'th': 'คำแนะนำความปลอดภัย',
    'en': 'Safety Tips',
    'zh': '安全提示',
    'ko': '안전 수칙',
    'ru': 'Советы по безопасности',
    'ja': '安全のヒント',
  },
  'safety_tip_1': {
    'th': 'เก็บพาสปอร์ตและเอกสารสำคัญไว้ในที่ปลอดภัย พกสำเนาแยกไว้ต่างหาก',
    'en': 'Keep your passport and important documents in a safe place; carry copies separately.',
    'zh': '将护照和重要证件存放在安全的地方，并随身携带副本。',
    'ko': '여권과 중요 서류는 안전한 곳에 보관하고, 사본은 따로 챙기세요.',
    'ru': 'Храните паспорт и важные документы в надёжном месте; берите с собой отдельные копии.',
    'ja': 'パスポートや重要な書類は安全な場所に保管し、コピーは別に持ち歩きましょう。',
  },
  'safety_tip_2': {
    'th': 'ตกลงราคาหรือใช้มิเตอร์ก่อนขึ้นแท็กซี่หรือตุ๊กตุ๊ก',
    'en': 'Agree on a fare or use the meter before taking a taxi or tuk-tuk.',
    'zh': '乘坐出租车或嘟嘟车前，请先确认价格或使用计价器。',
    'ko': '택시나 뚝뚝을 타기 전에 요금을 미리 정하거나 미터기를 사용하세요.',
    'ru': 'Перед поездкой на такси или тук-туке договоритесь о цене или используйте счётчик.',
    'ja': 'タクシーやトゥクトゥクに乗る前に料金を確認するか、メーターを使用しましょう。',
  },
  'safety_tip_3': {
    'th': 'บันทึกเบอร์ฉุกเฉินไว้: ตำรวจท่องเที่ยว 1155, เหตุฉุกเฉิน 191',
    'en': 'Save emergency numbers: Tourist Police 1155, Emergency 191.',
    'zh': '保存紧急电话：旅游警察 1155，紧急求助 191。',
    'ko': '긴급 전화번호를 저장하세요: 관광경찰 1155, 응급 191.',
    'ru': 'Сохраните номера экстренных служб: туристическая полиция 1155, экстренная помощь 191.',
    'ja': '緊急連絡先を保存しましょう：観光警察 1155、緊急通報 191。',
  },
  'safety_tip_4': {
    'th': 'ตรวจสอบสภาพอากาศและประกาศเตือนน้ำท่วมก่อนเดินทางไปยังพื้นที่ที่ได้รับผลกระทบ',
    'en': 'Check weather and flood advisories before traveling to affected areas.',
    'zh': '前往受影响地区前，请查看天气和洪水预警信息。',
    'ko': '영향을 받는 지역으로 이동하기 전에 날씨와 홍수 경보를 확인하세요.',
    'ru': 'Перед поездкой в пострадавшие районы проверьте прогноз погоды и предупреждения о наводнениях.',
    'ja': '影響を受けている地域へ行く前に、天気と洪水情報を確認しましょう。',
  },
  'safety_tip_5': {
    'th': 'ดื่มน้ำให้เพียงพอและหลีกเลี่ยงแสงแดดจัดในช่วงเวลาที่ร้อนที่สุด',
    'en': 'Stay hydrated and limit sun exposure during peak hours.',
    'zh': '请保持充足水分，并在高温时段减少日晒。',
    'ko': '충분히 수분을 섭취하고 햇볕이 강한 시간대에는 노출을 줄이세요.',
    'ru': 'Пейте достаточно воды и избегайте долгого пребывания на солнце в часы пик.',
    'ja': '十分な水分を取り、日差しが強い時間帯の外出は控えましょう。',
  },
  'safety_tip_6': {
    'th': 'หลีกเลี่ยงการเดินคนเดียวในพื้นที่ที่ไม่คุ้นเคยช่วงดึก',
    'en': 'Avoid walking alone in unfamiliar areas late at night.',
    'zh': '深夜请避免在不熟悉的地区独自步行。',
    'ko': '늦은 밤에는 낯선 지역에서 혼자 걷는 것을 피하세요.',
    'ru': 'Избегайте прогулок в одиночку по незнакомым районам в позднее время.',
    'ja': '夜遅くに不慣れな場所を一人で歩くのは避けましょう。',
  },
  'safety_tip_7': {
    'th': 'เปรียบเทียบราคาก่อนซื้อสินค้าหรือบริการ',
    'en': 'Compare prices before purchasing goods or services.',
    'zh': '购买商品或服务前请先比较价格。',
    'ko': '상품이나 서비스를 구매하기 전에 가격을 비교해 보세요.',
    'ru': 'Сравнивайте цены перед покупкой товаров или услуг.',
    'ja': '商品やサービスを購入する前に価格を比較しましょう。',
  },
  'safety_tip_8': {
    'th': 'เก็บสำเนาดิจิทัลของเอกสารและข้อมูลประกันการเดินทางไว้เสมอ',
    'en': 'Keep digital copies of your documents and travel insurance information.',
    'zh': '请保留证件和旅行保险信息的电子副本。',
    'ko': '서류와 여행자 보험 정보를 디지털 사본으로 보관하세요.',
    'ru': 'Храните цифровые копии документов и информации о туристической страховке.',
    'ja': '書類と旅行保険情報のデジタルコピーを保管しておきましょう。',
  },
  'profile_tagline': {
    'th': 'ความปลอดภัยของคุณคือสิ่งสำคัญที่สุด',
    'en': 'Your Safety, Our Priority',
    'zh': '您的安全，我们的首要任务',
    'ko': '당신의 안전이 최우선입니다',
    'ru': 'Ваша безопасность — наш приоритет',
    'ja': 'あなたの安全を第一に',
  },
  'profile_current_location': {
    'th': 'ตำแหน่งปัจจุบัน', 'en': 'Current Location', 'zh': '当前位置', 'ko': '현재 위치', 'ru': 'Текущее местоположение', 'ja': '現在の位置',
  },
  'profile_update_location': {
    'th': 'อัปเดตตำแหน่งของฉัน', 'en': 'Update My Location', 'zh': '更新我的位置', 'ko': '내 위치 업데이트', 'ru': 'Обновить моё местоположение', 'ja': '位置情報を更新',
  },
  'profile_location_placeholder': {
    'th': 'แตะปุ่มด้านล่างเพื่อตรวจหาตำแหน่งของคุณ',
    'en': 'Tap the button below to detect your location',
    'zh': '点击下方按钮以检测您的位置',
    'ko': '아래 버튼을 눌러 위치를 확인하세요',
    'ru': 'Нажмите кнопку ниже, чтобы определить ваше местоположение',
    'ja': '下のボタンをタップして位置を取得しましょう',
  },
  'profile_location_denied': {
    'th': 'ไม่ได้รับอนุญาตให้เข้าถึงตำแหน่ง กรุณาเปิดสิทธิ์การเข้าถึงตำแหน่งในตั้งค่า',
    'en': 'Location permission denied. Please enable location access in settings.',
    'zh': '位置权限被拒绝。请在设置中启用位置访问权限。',
    'ko': '위치 권한이 거부되었습니다. 설정에서 위치 접근을 허용해 주세요.',
    'ru': 'Доступ к местоположению запрещён. Включите его в настройках.',
    'ja': '位置情報の権限が拒否されました。設定で位置情報を許可してください。',
  },
  'profile_location_error': {
    'th': 'ไม่สามารถดึงตำแหน่งได้ในขณะนี้',
    'en': 'Unable to get your location right now',
    'zh': '目前无法获取您的位置',
    'ko': '지금은 위치를 가져올 수 없습니다',
    'ru': 'Не удалось определить местоположение',
    'ja': '現在、位置情報を取得できません',
  },
  'profile_emergency_help_center': {
    'th': 'ศูนย์ช่วยเหลือฉุกเฉิน', 'en': 'Emergency Help Center', 'zh': '紧急求助中心', 'ko': '응급 지원 센터', 'ru': 'Центр экстренной помощи', 'ja': '緊急ヘルプセンター',
  },
  'profile_call': {
    'th': 'โทร', 'en': 'Call', 'zh': '拨打', 'ko': '전화', 'ru': 'Позвонить', 'ja': '電話',
  },
  'profile_tourist_police': {
    'th': 'ตำรวจท่องเที่ยว', 'en': 'Tourist Police', 'zh': '旅游警察', 'ko': '관광경찰', 'ru': 'Туристическая полиция', 'ja': '観光警察',
  },
  'profile_police': {
    'th': 'ตำรวจ', 'en': 'Police', 'zh': '警察', 'ko': '경찰', 'ru': 'Полиция', 'ja': '警察',
  },
  'profile_ambulance': {
    'th': 'รถพยาบาล', 'en': 'Ambulance', 'zh': '救护车', 'ko': '구급차', 'ru': 'Скорая помощь', 'ja': '救急車',
  },
  'map_search_hint': {
    'th': 'ค้นหาสถานที่ เช่น กรุงเทพฯ, สุขุมวิท',
    'en': 'Search location e.g. Bangkok, Sukhumvit',
    'zh': '搜索地点，例如曼谷、素坤逸',
    'ko': '장소 검색 예: 방콕, 수쿰빗',
    'ru': 'Поиск места, напр. Бангкок, Сукхумвит',
    'ja': '場所を検索 例：バンコク、スクンビット',
  },
  'scanner_instructions_title': {
    'th': 'สแกนเมนูหรือป้ายราคา',
    'en': 'Scan a Menu or Price Tag',
    'zh': '扫描菜单或价格标签',
    'ko': '메뉴 또는 가격표 스캔',
    'ru': 'Сканируйте меню или ценник',
    'ja': 'メニューや価格表をスキャン',
  },
  'scanner_instructions_subtitle': {
    'th': 'ถ่ายรูปรายการราคา หรือถ่ายรูปอาหารเพื่อให้ AI ช่วยระบุเมนูและเทียบราคา',
    'en': 'Photograph a price list, or just the dish itself — AI will identify it and compare prices',
    'zh': '拍摄价目表，或直接拍摄菜品，AI 将识别并比较价格',
    'ko': '가격표를 찍거나 음식 사진만 찍어도 AI가 메뉴를 식별하고 가격을 비교해 드려요',
    'ru': 'Сфотографируйте прайс-лист или просто блюдо — ИИ распознает его и сравнит цены',
    'ja': '価格表を撮影するか、料理だけを撮影してもAIがメニューを識別して価格を比較します',
  },
  'scanner_capture_button': {
    'th': 'สแกนเลย', 'en': 'Scan Now', 'zh': '立即扫描', 'ko': '지금 스캔', 'ru': 'Сканировать', 'ja': '今すぐスキャン',
  },
  'scanner_processing': {
    'th': 'กำลังวิเคราะห์ภาพ...',
    'en': 'Analyzing image...',
    'zh': '正在分析图像...',
    'ko': '이미지 분석 중...',
    'ru': 'Анализ изображения...',
    'ja': '画像を解析中...',
  },
  'scanner_identifying': {
    'th': 'กำลังวิเคราะห์เมนูด้วย AI...',
    'en': 'Identifying dish with AI...',
    'zh': '正在用 AI 识别菜品...',
    'ko': 'AI로 메뉴를 분석하는 중...',
    'ru': 'Распознавание блюда с помощью ИИ...',
    'ja': 'AIでメニューを識別中...',
  },
  'scanner_ai_identified': {
    'th': 'AI ระบุเมนู', 'en': 'AI Identified', 'zh': 'AI 识别', 'ko': 'AI 식별됨', 'ru': 'Определено ИИ', 'ja': 'AI識別',
  },
  'scanner_reference_range': {
    'th': 'ช่วงราคาทั่วไปสำหรับเมนูนี้',
    'en': 'Typical Price Range for This Dish',
    'zh': '此菜品的一般价格范围',
    'ko': '이 메뉴의 일반적인 가격대',
    'ru': 'Типичный диапазон цен для этого блюда',
    'ja': 'このメニューの一般的な価格帯',
  },
  'scanner_view_location': {
    'th': 'ดูบนแผนที่', 'en': 'View on Map', 'zh': '在地图上查看', 'ko': '지도에서 보기', 'ru': 'Посмотреть на карте', 'ja': '地図で見る',
  },
  'scanner_no_match_found': {
    'th': 'ไม่พบรายการที่ตรงกัน ลองถ่ายรายการราคาให้ชัดเจนขึ้น หรือถ่ายภาพอาหารให้เห็นจานชัดๆ',
    'en': 'No matching items found. Try a clearer photo of the price list or the dish.',
    'zh': '未找到匹配的项目。请尝试拍摄更清晰的价目表或菜品照片。',
    'ko': '일치하는 항목을 찾지 못했습니다. 가격표나 음식 사진을 더 선명하게 찍어보세요.',
    'ru': 'Совпадений не найдено. Сделайте более чёткое фото прайс-листа или блюда.',
    'ja': '一致する項目が見つかりません。価格表または料理の写真をより鮮明に撮影してください。',
  },
  'scanner_scan_again': {
    'th': 'สแกนอีกครั้ง', 'en': 'Scan Again', 'zh': '重新扫描', 'ko': '다시 스캔', 'ru': 'Сканировать снова', 'ja': '再スキャン',
  },
  'scanner_results_title': {
    'th': 'ผลการสแกน', 'en': 'Scan Results', 'zh': '扫描结果', 'ko': '스캔 결과', 'ru': 'Результаты сканирования', 'ja': 'スキャン結果',
  },
  'scanner_detected_price': {
    'th': 'ราคาที่ตรวจพบ', 'en': 'Detected Price', 'zh': '检测到的价格', 'ko': '감지된 가격', 'ru': 'Обнаруженная цена', 'ja': '検出された価格',
  },
  'scanner_typical_range': {
    'th': 'ช่วงราคาทั่วไป', 'en': 'Typical Range', 'zh': '一般价格范围', 'ko': '일반적인 가격대', 'ru': 'Типичный диапазон', 'ja': '一般的な価格帯',
  },
  'scanner_permission_denied': {
    'th': 'ไม่ได้รับอนุญาตให้เข้าถึงกล้อง กรุณาเปิดสิทธิ์การเข้าถึงกล้องในตั้งค่า',
    'en': 'Camera permission denied. Please enable camera access in settings.',
    'zh': '相机权限被拒绝。请在设置中启用相机访问权限。',
    'ko': '카메라 권한이 거부되었습니다. 설정에서 카메라 접근을 허용해 주세요.',
    'ru': 'Доступ к камере запрещён. Включите его в настройках.',
    'ja': 'カメラの権限が拒否されました。設定でカメラを許可してください。',
  },
  'scanner_error_generic': {
    'th': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
    'en': 'Something went wrong. Please try again.',
    'zh': '出错了，请重试。',
    'ko': '문제가 발생했습니다. 다시 시도해 주세요.',
    'ru': 'Что-то пошло не так. Попробуйте ещё раз.',
    'ja': '問題が発生しました。もう一度お試しください。',
  },
  'scanner_disclaimer': {
    'th': 'ข้อมูลนี้เป็นการประเมินจากข้อมูลสถิติและข้อมูลจากชุมชนเพื่อประกอบการตัดสินใจเท่านั้น ราคาจริงอาจแตกต่างกันได้',
    'en': 'This information is generated from statistical and community-based data and is intended for informational purposes only. Actual prices may vary.',
    'zh': '此信息基于统计和社区数据生成，仅供参考。实际价格可能有所不同。',
    'ko': '이 정보는 통계 및 커뮤니티 데이터를 기반으로 생성되었으며 참고용입니다. 실제 가격은 다를 수 있습니다.',
    'ru': 'Эта информация формируется на основе статистических и общественных данных и приведена исключительно в информационных целях. Фактические цены могут отличаться.',
    'ja': 'この情報は統計データとコミュニティデータに基づいて生成されたもので、参考情報です。実際の価格は異なる場合があります。',
  },
  'scanner_scan_location': {
    'th': 'ตำแหน่งที่ถ่ายภาพ', 'en': 'Scan Location', 'zh': '拍摄位置', 'ko': '촬영 위치', 'ru': 'Место съёмки', 'ja': '撮影位置',
  },
  'scanner_category_food': {
    'th': 'อาหาร', 'en': 'Food', 'zh': '食品', 'ko': '음식', 'ru': 'Еда', 'ja': '食べ物',
  },
  'scanner_category_transport': {
    'th': 'การเดินทาง', 'en': 'Transport', 'zh': '交通', 'ko': '교통', 'ru': 'Транспорт', 'ja': '交通',
  },
  'scanner_category_attraction': {
    'th': 'สถานที่ท่องเที่ยว', 'en': 'Attraction', 'zh': '景点', 'ko': '관광지', 'ru': 'Достопримечательности', 'ja': '観光地',
  },
  'scanner_other_matches': {
    'th': 'รายการที่พบเพิ่มเติม', 'en': 'Other Matches', 'zh': '其他匹配项', 'ko': '다른 검색 결과', 'ru': 'Другие совпадения', 'ja': 'その他の一致',
  },
  'variance_within': {
    'th': 'อยู่ในช่วงราคาทั่วไป', 'en': 'Within Typical Range', 'zh': '处于一般价格范围内', 'ko': '일반적인 가격대 내', 'ru': 'В пределах типичного диапазона', 'ja': '一般的な価格帯内',
  },
  'variance_above': {
    'th': 'สูงกว่าช่วงราคาทั่วไป', 'en': 'Above Typical Range', 'zh': '高于一般价格范围', 'ko': '일반적인 가격대보다 높음', 'ru': 'Выше типичного диапазона', 'ja': '一般的な価格帯より高い',
  },
  'variance_significant': {
    'th': 'มีความแตกต่างของราคาอย่างมีนัยสำคัญ', 'en': 'Significant Price Variation', 'zh': '价格差异显著', 'ko': '가격 차이가 상당함', 'ru': 'Значительное отклонение цены', 'ja': '価格差が大きい',
  },
  'variance_below': {
    'th': 'ต่ำกว่าช่วงราคาทั่วไป', 'en': 'Below Typical Range', 'zh': '低于一般价格范围', 'ko': '일반적인 가격대보다 낮음', 'ru': 'Ниже типичного диапазона', 'ja': '一般的な価格帯より低い',
  },
  'map_search_not_found': {
    'th': 'ไม่พบสถานที่นี้ ลองพิมพ์ชื่ออื่นดูนะครับ',
    'en': 'Location not found. Try a different place name.',
    'zh': '未找到该地点，请尝试其他名称。',
    'ko': '위치를 찾을 수 없습니다. 다른 이름을 입력해 보세요.',
    'ru': 'Место не найдено. Попробуйте другое название.',
    'ja': '場所が見つかりません。別の名前をお試しください。',
  },
};

/// Returns the localized string for [key] based on the app's current
/// locale, falling back to English if no translation exists.
String appText(BuildContext context, String key) {
  final code = Localizations.localeOf(context).languageCode;
  final entry = _appText[key];
  if (entry == null) return key;
  return entry[code] ?? entry['en'] ?? key;
}
